baseURL = "/"
languageCode = "en-us"
title = "Vamsi Talupula"
theme = "xmin"

ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$", "content/contact/.*"]
footnotereturnlinkcontents = "↩"

# for smart copyright line, leave this blank and check [params.copyright]
copyright = ""

disqusShortname = ""
googleAnalytics = "UA-132817962-1"

Paginate = 5
preserveTaxonomyNames = true

enableRobotsTXT = true # generate robots.txt

[markup]
[markup.highlight]
codeFences = true
noClasses = true
style = "github"

enableEmoji = true

# Missing translations will default to this content language
defaultContentLanguage = "en"

[params.info]
description = "Developing tools to help developers build a better and safer place"
title404 = "Nothing's here!"

[params.assets]

favicon = "favicon.ico"
customCSS = ["css/custom.css"]
customJS = ["js/custom.js"]
gopher = "" # used in 404 template ( Generator: https://gopherize.me )

[params.copyright]
prefix = ""
holder = "Vamsi Talupula"
startYear = "2017"
suffix = ""

[params.settings]
# date & time format: https://golang.org/pkg/time/
dateFormat = "2006, Jan 02"
listDateFormat = "2006, Jan 02"
archiveDateFormat = "Jan 02"
hideEntryNavigation = ["page"] # boolean / array of sections
hideEntryMeta = ["page"] # boolean / array of sections
showReadingTime = true
showLastmod = true
taxonomyCloudShuffle = false
accentColor = "#44ccff"
hideMainMenu = false
rtl = false

[params.sidebar]
enable = true

[params.widgets]
header = ["breadcrumbs"]
homepage = ["recent_posts"]
sidebar = ["about", "search", "sidebar_menu", "taxonomy_cloud"]
footer = ["social_menu"]

[params.opengraph.facebook]
admins = [] # array of Facebook IDs
appID = ""
pageID = ""

[params.opengraph.twitter]
page = "" # Twitter page username

[params.seo]
# Title Separator: - – — · • * ⋆ | ~ « » < >
titleSeparator = "•"

[params.social]
email = "tanavamsikrishna@outlook.com"
github = ""

[params.comments]
enable = false

# Isso: https://posativ.org/isso/
[params.comments.isso]
enable = false
scriptSrc = "" # "https://isso.example.com/js/embed.min.js"
dataAttrs = "" # "data-isso='https://isso.example.com' data-isso-require-author='true'"

[params.comments.staticman]
enable = true
apiEndpoint = "https://api.staticman.net/v2/entry"
maxDepth = 2
username = "achary"
repository = "engimo"
branch = "master"

# Utterances: https://utteranc.es
[params.comments.utterances]
enable = false
issueTerm = "pathname" # pathname / url / title

[params.comments.utterances.github]
username = "achary"
repository = "engimo"

[params.search]
client = "fuse" # algolia / fuse / lunr

[params.search.algolia]
appId = ""
indexName = ""
searchApiKey = ""

[taxonomies]
author = "authors"
category = "categories"
series = "series"
tag = "tags"

[permalinks]
page = "/:slug/"

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Articles"
url = "/posts"
weight = 2

# [[menu.main]]
# name = "About"
# url = "/about/"
# weight = 3

# [[menu.main]]
# name = "Categories"
# url = "/categories/"
# weight = 4

[[menu.main]]
name = "Tags"
url = "/tags/"
weight = 5

[[menu.main]]
name = "Code"
url = "./code"
identifier = "BitBucket"
weight = 4

# [[menu.main]]
# name = "Contact/Comment"
# url = "./contact/"
# weight = 3

[[menu.main]]
name = "Subscribe"
url = "/index.xml"
weight = 7

[params]
footer = "© Vamsi Talupula 2020"

[blackfriday]
hrefTargetBlank = true

[languages]
# edit this block for your own language
[languages.en]
lang = "en"
languageName = "English"
weight = 1
